# Paso 1: Entorno de compilación con Git y Maven
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app

# Copiamos lo que el .sh ya descargó
COPY . . 
# Compilamos el proyecto
RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
