# Usamos el JDK completo (no el JRE) porque Maven necesita compilar en caliente
FROM maven:3.9.6-eclipse-temurin-21
WORKDIR /app

# 1. Copiamos solo el pom.xml primero para descargar dependencias y ahorrar tiempo
COPY backend/pom.xml .
RUN mvn dependency:go-offline

# 2. Copiamos el resto del código
COPY backend/src ./src

# 3. Exponemos el puerto de la API y el de Debug (opcional)
EXPOSE 8080
EXPOSE 5005
