services:
  # --------------------------------------
  # BASE DE DATOS
  db:
    image: mysql:${MYSQL_VERSION}
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_HOST=%
#    ports:
#      - "${PORT_DATABASE}:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # --------------------------------------
  # BACKEND (Spring Boot)
  backend:
    build: 
      context: ../backend
      dockerfile: ../.config/Dockerfile.backend.dev
      args:
        PORT_BACKEND: ${PORT_BACKEND} 
    restart: always
    ports:
      - "${PORT_BACKEND}:8080"
      - "5005:5005"

    # --- SECCIÓN AUTO-RELOAD ---
    x-develop:
      watch:
        - path: ../backend/src
          action: sync
          target: /app/src
        - path: ../backend/pom.xml
          action: rebuild
    # --------------------------------------
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_ROOT_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${DB_URL}
      - DB_DRIVER=${DB_DRIVER} 
      - APP_BASE_URL=${APP_BASE_URL}
      - CORS_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - UPLOAD_DIR=/app/uploads
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
    volumes:
      - ../backend/uploads:/app/uploads
      - ../backend:/app:delegated
      - maven_data:/root/.m2
    command: >
      mvn spring-boot:run 
      -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

  # --------------------------------------
  # FRONTEND (React)
  frontend:
    build: 
      context: ../frontend
      dockerfile: ../.config/Dockerfile.frontend.dev
      args:
        PORT_FRONTEND: ${PORT_FRONTEND} 
    ports:
      - "${PORT_FRONTEND}:${PORT_FRONTEND}"
    depends_on:
      - backend
    stdin_open: true
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:${PORT_BACKEND}
    volumes:
      - ../frontend:/app:delegated      
      - /app/node_modules       
    command: npm run dev -- --host 0.0.0.0 --port ${PORT_FRONTEND}


volumes:
  db_data:
  maven_data:
  npm_cache:
